// Generated by Classiq.
// Classiq version: 0.49.0
// Creation timestamp: 2024-09-23T22:43:19.157175+00:00
// Random seed: 4168675763

OPENQASM 2.0;
include "qelib1.inc";
gate apply_to_all_expanded___4 q0,q1,q2,q3 {
  h q0;
  h q1;
  h q2;
  h q3;
}

gate main_hadamard_transform q0,q1,q2,q3 {
  apply_to_all_expanded___4 q0,q1,q2,q3;
}

gate rcccx q0,q1,q2,q3 {
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
}

gate rcccx_dg q0,q1,q2,q3 {
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
}

gate mcx q0,q1,q2,q3,q4 {
  h q4;
  cu1(pi/2) q3,q4;
  h q4;
  rcccx q0,q1,q2,q3;
  h q4;
  cu1(-pi/2) q3,q4;
  h q4;
  rcccx_dg q0,q1,q2,q3;
  c3sqrtx q0,q1,q2,q4;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4 {
  mcx q0,q1,q2,q3,q4;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1,q2,q3,q4 {
  x q0;
  x q1;
  x q2;
  x q3;
  mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4;
  x q0;
  x q1;
  x q2;
  x q3;
}

gate oracle_phase_kickback_oracle_function_arithmetic_equal_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1,q2,q3,q4;
}

gate oracle_phase_kickback_oracle_function_arithmetic_equal q0,q1,q2,q3,q4 {
  oracle_phase_kickback_oracle_function_arithmetic_equal_mcx_0 q0,q1,q2,q3,q4;
}

gate oracle_phase_kickback_oracle_function_arithmetic q0,q1,q2,q3,q4 {
  oracle_phase_kickback_oracle_function_arithmetic_equal q0,q1,q2,q3,q4;
}

gate oracle_phase_kickback_oracle_function q0,q1,q2,q3,q4 {
  oracle_phase_kickback_oracle_function_arithmetic q0,q1,q2,q3,q4;
}

gate main_oracle_phase_kickback q0,q1,q2,q3,q4 {
  x q4;
  h q4;
  oracle_phase_kickback_oracle_function q0,q1,q2,q3,q4;
  h q4;
  x q4;
}

qreg q[5];
main_hadamard_transform q[0],q[1],q[2],q[3];
main_oracle_phase_kickback q[0],q[1],q[2],q[3],q[4];
